drop table department if exists;
drop table employee if exists;
drop table profession if exists;

create table department (
    id bigint generated by default as identity primary key,
    name varchar(255),
    note TEXT,
    parent_department_id bigint);

create table employee (
    id bigint generated by default as identity primary key,
    first_name varchar(255),
    second_name varchar(255),
    patronymic varchar(255),
    note TEXT,
    profession_id bigint,
    department_id bigint);

create table profession (
    id bigint generated by default as identity primary key,
    name varchar(255),
    note TEXT);
